<section class="content-header">
    <h1> Detalhes do pedido Nº <?php echo $this->view->order['idorder'] ?></h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/admin/orders">Pedidos</a></li>
        <li class="active"><a href="/admin/order?idorder=<?php echo $this->view->order['idorder'] ?>">Pedido Nº <?php echo $this->view->order['idorder'] ?></a></li>
    </ol>
</section>

<section class="invoice content">
    <!-- title row -->
    <div class="row">
        <div class="col-xs-12">
        <h2 class="page-header">
            <small class="pull-right">Data: <?php echo date('d/m/Y') ?></small>
        </h2>
        </div>
        <!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
        De
        <address>
            <strong>E-Commerce Stores</strong><br>
            Terceira Atravessa, 510 - Caéstes II<br>
            Avenida A - PE, 53540-010<br>
            Telefone: (81) 99546-9010<br>
            E-mail: suporteEcommerce@suporte.com.br
        </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
        Para
        <address>
            <strong><?php echo $this->view->order['desperson'] ?></strong><br>
            <?php echo $this->view->order['desaddress'] ?>, <?php echo $this->view->order['descomplement'] ?><br>
            <?php echo $this->view->order['descity'] ?> - <?php echo $this->view->order['desstate'] ?> - Nº <?php echo $this->view->order['desnumber'] ?>, <?php echo $this->view->order['deszipcode'] ?><br>
            Telefone: <?php echo $this->view->order['nrphone'] ?><br>
            E-mail: <?php echo $this->view->order['desemail'] ?>
        </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
        <b>Pedido #<?php echo $this->view->order['idorder'] ?></b><br>
        <br>

        <?php
            $data = new DateTime($this->view->order['dataRegistro']);
            $data = str_replace('-','/',$data->format('d-m-Y H:i'));
        ?>

        <b>Emitido em:</b> <?php echo $data ?><br>
        <b>Pago em:</b> <?php echo $data ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Cód</th>
                <th>Produto</th>
                <th>Valor U</th>
                <th>Subtotal</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->view->products as $key => $product) {?>
                <tr>
                    <td><?php echo $product['idproduct'] ?></td>
                    <td><small><?php echo $product['desproduct'] ?> </small><sup><b>X<?php echo $product['quantity'] ?></b></sub></td>
                    <td>R$<?php echo number_format($product['vlprice'],2,',','.') ?></td>
                    <td>R$<?php echo number_format($product['vlprice'] * $product['quantity'],2,',','.') ?></td>
                </tr>
            <?php }?>

            </tbody>
        </table>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">

            <p class="lead">Forma de Pagamento</p>
            
            <table class="table">
                <tbody>
                <tr>
                    <th style="width:180px;">Método de Pagamento:</th>
                    <td><?php echo $this->view->order['despayment']?></td>
                </tr>
                <tr>
                    <th>Parcelas:</th>
                    <?php if($this->view->order['idpayment'] == 1){ ?>
                        <td>1x</td>
                    <?php }else { ?>
                        <td><?php echo $this->view->order['desparcelas'] ?>x</td>
                    <?php } ?>
                </tr>
                <tr>
                    <th>Valor da Parcela:</th>
                    <td>R$<?php echo number_format($this->view->order['vltotal'],2,',','.') ?></td>
                </tr>
                <tr>
                    <th style="width:180px;">Status: </th>
                    <td><?php echo $this->view->order['desstatus']?></td>
                </tr>
               
                </tbody>
            </table>

        </div>
        <!-- /.col -->
        <div class="col-xs-6">
        <p class="lead">Resumo do Pedido</p>

        <div class="table-responsive">
            <table class="table">
            <tbody><tr>
                <th style="width:50%">Subtotal:</th>
                <td>R$<?php echo number_format($this->view->order['vltotal'] - $this->view->order['vlfreight'] ,2,',','.') ?></td>
            </tr>
            <tr>
                <th>Frete:</th>
                <td>R$<?php echo number_format($this->view->order['vlfreight'],2,',','.') ?></td>
            </tr>
            <tr>
                <th>Total:</th>
                <td>R$<?php echo number_format($this->view->order['vltotal'],2,',','.') ?></td>
            </tr>
            </tbody></table>
        </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- this row will not appear when printing -->
    <div class="row no-print">
        <div class="col-xs-12">
            <button type="button" onclick="window.location.href = '/admin/order/status?idorder=<?php echo $this->view->order['idorder']?>'" class="btn btn-default pull-left" style="margin-left: 5px;">
                <i class="fa fa-pencil"></i> Editar Status
            </button>
            <button type="button" onclick="window.open('/admin/boleto?idorder=<?php echo $this->view->order['idorder']?>')" class="btn btn-default pull-left" style="margin-left: 5px;">
                <i class="fa fa-barcode"></i> Boleto
            </button>

            
            <button type="button" onclick="window.print()" class="btn btn-primary pull-right" style="margin-right: 5px;">
                <i class="fa fa-print"></i> Imprimir Comprovante
            </button>
        </div>
    </div>
</section>

<div class="clearfix"></div>
<script>$('.treeview#order').addClass('active');</script>
<script>$('.treeview#order li.2').addClass('active');</script>
