<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        <li id="categorias" onclick="openCategoryMenu()"><a href="#"><i class="fa-solid fa-ellipsis-vertical"></i> Categorias</a></li>
                        
                        <?php if(isset($_SESSION['auth']) && $_SESSION['auth']){ ?>
                            <li><a href="#"><i class="fa fa-user"></i> Minha Conta</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Lista de Desejos</a></li>
                            <li><a href="/cart"><i class="fa fa-shopping-cart"></i> Meu Carrinho</a></li>
                            <?php if(isset($_SESSION['inadmin']) && $_SESSION['inadmin'] == 1){ ?>
                                <li><a href="/admin"><i class="fa-solid fa-screwdriver-wrench"></i> Admin</a></li>
                            <?php } ?>
                            <li><a href="/logout"><i class="fa fa-close"></i> Sair</a></li>
                        <?php }else{ ?>
                            <li><a href="/login"><i class="fa fa-lock"></i> Login</a></li>
                        <?php }?>
                    </ul>
                </div>
            </div>

            <div class="col-md-4">
                <div class="header-right">
                    <ul class="list-unstyled list-inline">
                        <li class="dropdown dropdown-small">
                            <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">moeda :</span><span class="value">BRL </span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">BRL</a></li>
                                <li><a href="#">USD</a></li>
                            </ul>
                        </li>

                        <li class="dropdown dropdown-small">
                            <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">linguagem :</span><span class="value">Português </span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Português</a></li>
                                <li><a href="#">Inglês</a></li>
                                <li><a href="#">Espanhol</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="site-branding-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="logo">
                    <h1><a href="/">Home<img src=""></a></h1>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="shopping-item">
                    <a href="/cart">Carrinho - <span class="cart-amunt">R$100</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End site branding area -->

<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="itemMenu">
                    <li class="active" id="home"><a href="#">Home</a></li>
                    <li id="prod"><a href="/produtos">Produtos</a></li>
                    <li id="cart"><a href="/cart">Carrinho</a></li>
                </ul>
            </div>
        </div>
    </div>
</div> 