<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        <?php if(isset($_SESSION['User']['inadmin']) && $_SESSION['User']['inadmin'] == 1){ ?>
                            <li><a href="/admin"><i class="fa-solid fa-screwdriver-wrench"></i> Admin</a></li>
                        <?php } ?>
                        <li><a href="/logout"><i class="fa fa-close"></i> Sair</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="itemMenu">
                    <li class="active" id="home"><a href="/">Home</a></li>
                    <li id="profile"><a href="/profile">Perfil</a></li>
                    <li id="cart"><a href="/cart">Carrinho</a></li>
                    <li id="pedidos"><a href="/pedidos">Pedidos</a></li>
                    <li id="changePass"><a href="/profile/changePass">Alterar Senha</a></li>
                </ul>
            </div>
        </div>
    </div>
</div> 