<aside class="main-sidebar">

    <section class="sidebar">

        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?php echo empty($_SESSION['perfil']) ? "https://via.placeholder.com/150" : "/img/perfil/".$_SESSION['perfil']?>" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?php echo $_SESSION['desperson'] ?></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>

        <ul class="sidebar-menu">
            <li class="header text-center">Menu</li>
            <li class="treeview" id="logout">
                <a href="/">
                    <i class="fa-solid fa-door-closed"></i>
                    <span>Sair do Admin</span>
                </a>
            </li>
            <li class="treeview" id="home">
                <a href="/admin">
                    <i class="fa-solid fa-home"></i>
                    <span>Home</span>
                </a>
            </li>
            
            <li class="treeview" id="user">
                <a href="">
                    <i class="fa-solid fa-users"></i>
                    <span>Usuarios</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/users">
                            <i class="fa-solid fa-user"></i>
                            Listar
                        </a>
                    </li>
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/users/create">
                            <i class="fa-solid fa-user-plus"></i>
                            Criar
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview" id="categorie">
                <a href="#">
                    <i class="fa-solid fa-diagram-project"></i>
                     
                    <span>Categorias</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/categorias">
                            <i class="fa-solid fa-cart-shopping"></i>      
                            Listar
                        </a>
                    </li>
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/categoria/create">
                            <i class="fa-solid fa-cart-plus"></i>
                            Criar
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview" id="prod">
                <a href="#">
                    <i class="fa-solid fa-barcode"></i>
                     
                    <span>Produtos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/produtos">
                            <i class="fa-solid fa-table-list"></i>   
                            Listar
                        </a>
                    </li>
                    <li class="boderLiTreeviewMenu">
                        <a href="/admin/produto/create">
                            <i class="fa-regular fa-square-plus"></i>
                            Criar
                        </a>
                    </li>
                </ul>
            </li>
            
            <li class="treeview" id="">
                <a href="/logout">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Sair</span>
                </a>
            </li>
        </ul>
    </section>
</aside>