<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->view->title ?> | E-Commerce |</title>
    <style>
        @page {
            size: auto;
            margin: 0;
        }
        @print{
            @page :footer {
                display: none
            }
        
            @page :header {
                display: none
            }
        }
        @media print {
            @page {
                margin-top: 0;
                margin-bottom: 0;
            }
            body {
                padding-top: 72px;
                padding-bottom: 72px ;
            }
        }
    </style>
</head>
<body>
    <script>window.print()</script>
</body>
</html>