
<?php $this->loadComponent('title') ?>
<?php $cart = $this->view->cart ?>
<?php $address = $this->view->address ?>
<div class="single-product-area">
	<div class="zigzag-bottom"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="product-content-right">
					<form action="/checkout/checkinfo" class="checkout" method="post">
						<div id="customer_details" class="col2-set">
							<div class="row">
								<div class="col-md-12">

									<div class="woocommerce-billing-fields">
										<h3>Endereço de entrega</h3>
										<p id="billing_address_1_field" class="form-row form-row-wide address-field validate-required">
											<label class="" for="billing_address_1">Cep <abbr title="required" class="required">*</abbr>
											</label>
                                            <input type="text" value="<?php echo $address['deszipcode'] ?>" placeholder="00000-000" id="billing_address_1" name="cep" class="input-text " required>
                                            <input type="submit" value="Atualizar CEP" id="place_order" class="button alt" formaction="/cart/freight?redirect=checkout" formmethod="POST">
										</p>
										<p id="billing_address_1_field" class="form-row form-row-wide address-field validate-required">
											<label class="" for="billing_address_1">Endereço <abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" value="<?php echo $address['desaddress'] ?>" placeholder="Logradouro/Rua" id="billing_address_1" name="desaddress" class="input-text" readonly required>
										</p>
										<p id="billing_address_2_field" class="form-row form-row-wide address-field">
											<label class="" for="billing_address_1">Complemento</label>
											<input type="text" value="<?php echo $address['descomplement'] ?>"" placeholder="Complemento (opcional)" id="billing_address_2" name="descomplement" class="input-text" >
                                        </p>
                                        <p id="billing_district_field" class="form-row form-row-wide address-field validate-required" data-o_class="form-row form-row-wide address-field validate-required">
											<label class="" for="billing_district">Bairro <abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" value="<?php echo $address['desdistrict'] ?>"" placeholder="Cidade" id="billing_district" name="desdistrict" class="input-text" readonly required>
										</p>
										<p id="billing_city_field" class="form-row form-row-wide address-field validate-required" data-o_class="form-row form-row-wide address-field validate-required">
											<label class="" for="billing_city">Cidade <abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" value="<?php echo $address['descity'] ?>"" placeholder="Cidade" id="billing_city" name="descity" class="input-text" readonly required>
										</p>
										<p id="billing_state_field" class="form-row form-row-first address-field validate-state" data-o_class="form-row form-row-first address-field validate-state">
											<label class="" for="billing_state">Estado
												<abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" id="billing_state" name="desstate" placeholder="Estado" value="<?php echo $address['desstate'] ?>"" class="input-text" readonly required> 
										</p>
										<p id="billing_state_field" class="form-row form-row-first address-field validate-state" data-o_class="form-row form-row-first address-field validate-state">
											<label class="" for="billing_state">Número
												<abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" id="billing_state" name="desnumber" placeholder="Número" value="<?php echo $address['desnumber'] ?>"" class="input-text">
										</p>
										<p id="billing_country_field" class="form-row form-row-first address-field validate-country" data-o_class="form-row form-row-first address-field validate-country">
											<label class="" for="billing_country">País
												<abbr title="required" class="required">*</abbr>
											</label>
											<input type="text" id="billing_state" name="descountry" placeholder="País" value="<?php echo $address['descountry'] ?>"" class="input-text" readonly required>
										</p>
										<p>
											<label class="" for="billing_Payment">Metodo de pagamento
												<abbr title="required" class="required">*</abbr>
											</label>
											<select name="despayment" class="select-control" id="billing_Payment" required onchange="changeParcelas(this)">
												<option value="">-- Escolha um Método de Pagamento --</option>
												<?php foreach ($this->view->payments as $key => $payment) {?>
													<option value="<?php echo $payment['idpayment'] ?>">
														<?php echo $payment['despayment'] ?>
													</option>
												<?php }?>
											</select>

											
											
										</p>
										<p id="parcelas" style="display: none;">
											<label class="" for="billing_parcelas">Parcelas
												<abbr title="required" class="required">*</abbr>
											</label>
											<select name="desparcelas" class="select-control parcelas" id="billing_parcelas" required onchange="changeParcelas()" >
												<option value="">-- Escolha uma Parcela --</option>
													<option value="1">1</option>
													<option value="2">2</option>
													<option value="3">3</option>
													<option value="4">4</option>
													<option value="5">5</option>
													<option value="6">6</option>
													<option value="7">7</option>
													<option value="8">8</option>
													<option value="9">9</option>
													<option value="10">10</option>
													<option value="11">11</option>
													<option value="12">12</option>
											</select>
										</p>
										
										
										<div class="clear"></div>
										<h3 id="order_review_heading" style="margin-top:30px;">Detalhes do Pedido</h3>
										<div id="order_review" style="position: relative;">
											<table class="shop_table">
												<thead>
													<tr>
														<th class="product-name">Produto</th>
														<th class="product-total">Total</th>
													</tr>
												</thead>
												<tbody>
                                                    <?php foreach ($this->view->productsCart as $key => $produto) {?>
														<tr class="cart_item">
															<td class="product-name">
																<?php echo $produto['desproduct'] ?><strong class="product-quantity">× <?php echo $produto['quantity'] ?></strong> 
															</td>
															<td class="product-total">
																<span class="amount">R$ <?php echo number_format($produto['total'],2,',','.') ?></span>
															</td>
														</tr>

													<?php } ?>
                                                    
												</tbody>
												<tfoot>
													<tr class="cart-subtotal">
														<th>Subtotal</th>
														<td><span class="amount">R$<?php echo number_Format($_SESSION['Cart']['total'],2,',','.') ?></span>
														</td>
													</tr>
													<tr class="shipping">
														<th>Frete</th>
														<td>
															R$ 
															<?php echo 
															!empty($_SESSION['Cart']['freight']) ?
															number_Format($_SESSION['Cart']['freight'],2,',','.') 
															: "0,00" ?>
														</td>
													</tr>
													<tr class="shipping">
														<th>Prazo</th>
														<td>
															<?php echo !empty($_SESSION['Cart']['nrdays']) ? $_SESSION['Cart']['nrdays'] : "0" ?>
															Dias Úteis
														</td>
													</tr>
													
													<tr class="order-total">
														<th>Total do Pedido</th>
														<td><strong><span class="amount">R$ <?php echo number_Format(($_SESSION['Cart']['total'] + $_SESSION['Cart']['freight']),2,',','.') ?></span></strong> </td>
													</tr>
												</tfoot>
											</table>
											<div id="payment">
												<div class="form-row place-order">
													<input type="submit" data-value="Place order" value="Continuar" id="place_order" class="button alt">
												</div>
												<div class="clear"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>activeItem('check')</script>

<script>
	const changeParcelas = () => {
		let mtd = document.querySelector('#billing_Payment').value

		switch (mtd) {
			case '1':
				disableParcelas()
				break;
			case '2':
				disableParcelas()
				break;
			case '3':
				enableParcelas()
				console.log(mtd)

				break;
			
			default:
				disableParcelas()
				break;
		}
	}

	const disableParcelas = () => {
		document.querySelector('#parcelas').style.display='none'
	}
	const enableParcelas = () => {
		document.querySelector('#parcelas').style.display='block'
	}
	
</script>