<?php $this->view->subtotal = []?>
<?php $this->view->valor = 0?>
<?php $this->view->product = 0?>
<form method="post" action="#">
    <table cellspacing="0" class="shop_table cart">
        <thead>
            <tr>
                <th class="product-remove" style="width: 20px;">&nbsp;</th>
                <th class="product-thumbnail" style="width: 140px;">&nbsp;</th>
                <th class="product-name">Produto</th>
                <th class="product-price" style="width: 200px;">Preço</th>
                <th class="product-quantity" style="width: 80px;">Quantidade</th>
                <th class="product-subtotal" style="width: 200px;">Total</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->view->productsCart as $key => $produto){ ?>
                <?php 
                    $this->view->valor += $produto['total'];
                    $this->view->product += $produto['quantity'];
                    array_push($this->view->subtotal, $this->view->valor);

                    $_SESSION['Cart']['total'] = $this->view->subtotal[count($this->view->subtotal)-1];
                    $_SESSION['Cart']['quantity'] = $this->view->product;
                ?>;

                <tr class="cart_item">
                    <td class="product-remove">
                        <a title="Remove this item" class="remove" href="/cart/remove?idProduct=<?php echo $produto['idproduct'] ?>&all=true">×</a>
                    </td>

                    <td class="product-thumbnail">
                        <a href="/productsDetails?url=<?php echo $produto['desurl'] ?>"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="<?php echo $produto['photo'] ?>"></a>
                    </td>

                    <td class="product-name">
                        <a href="/productsDetails?url=<?php echo $produto['desurl'] ?>">
                            <?php echo $produto['desproduct'] ?>
                        </a>
                    </td>

                    <td class="product-price">
                        <span class="amount">R$ <?php echo number_format($produto['vlprice'], 2, ',', '.') ?></span>
                    </td>

                    <td class="product-quantity">
                        <div class="quantity buttons_added">
                            <a href="/cart/remove?idProduct=<?php echo $produto['idproduct'] ?>&all=false" class="minus">-</a>
                            <input type="number" size="4" class="input-text qty text" title="Qty" value="<?php echo $produto['quantity'] ?>" readonly style="text-align: center;">
                            <a href="/cart/add?idProduct=<?php echo $produto['idproduct'] ?>" class="plus">+</a>
                        </div>
                    </td>

                    <td class="product-subtotal">
                        <span class="amount">R$ <?php echo number_format($produto['total'], 2, ',', '.') ?></span>
                    </td>
                </tr>
            <?php }?>

            <tr>
                <td class="actions" colspan="6">
                    <div class="coupon">
                        <label for="coupon_code">Cupom:</label>
                        <input type="text" placeholder="Coupon code" value="" id="coupon_code" class="input-text" name="coupon_code">
                        <input type="submit" value="Aplicar" name="apply_coupon" class="button">
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</form>