<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        <?php if(isset($_SESSION['auth']) && $_SESSION['auth']){ ?>
                            <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
                        <?php }else{ ?>
                            <li><a href="/login"><i class="fa fa-close"></i> sair</a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>