
<?php $this->loadComponent('title') ?>

<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">                
            <div class="col-md-12">
                <div class="cart-collaterals">
                    <h2>Meus Pedidos</h2>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Valor Total</th>
                            <th>Status</th>
                            <th>Endereço</th>
                            <th>Data</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(!empty($this->view->orders)){ ?>
                            <?php foreach ($this->view->orders as $key => $order) {?>
                                <?php
                                    $data = new DateTime($order['dataRegistro']);
                                    $data = str_replace('-','/',$data->format('d-m-Y H:i'));
                                ?>
                                <tr>
                                    <th scope="row"><?php echo $key+1 ?></th>
                                    <td>R$ <?php echo number_format($order['vltotal'],2,',','.')?></td>
                                    <td><?php echo $order['desstatus'] ?></td>
                                    <td>
                                        <?php echo $order['desaddress'] ?>,
                                        <?php echo $order['desdistrict'] ?>, 
                                        <?php echo $order['descity'] ?> - , 
                                        <?php echo $order['desstate'] ?>
                                        CEP: <?php echo $order['deszipcode'] ?>
                                    </td>
                                    <td><?php echo $data ?></td>
                                    <td style="width:222px;">
                                        <a class="btn btn-success" href="/payment?idorder=<?php echo $order['idorder'] ?>" role="button">Imprimir Boleto</a>
                                        <a class="btn btn-default" href="/pedidoDetails?idorder=<?php echo $order['idorder'] ?>" role="button">Detalhes</a>
                                    </td>
                                </tr>
                            <?php }?>
                        <?php }else{?>
                            <div class="alert alert-info">
                                Nenhum pedido foi encontrado.
                            </div>
                        <?php }?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<script>activeItem('pedidos')</script>