<section class="content-header">
    <h1> Todas as Categorias</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/admin/categorias">Categorias</a></li>
        <li class="active"><a href="/admin/categorias">Todas</a></li>
    </ol>
</section>
<section class="content">
    
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Registro</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->categories as $key => $value) {?>
                                <tr>
                                    <td><?php echo $key+1 ?></td>
                                    <td><?php echo $value['descategory'] ?></td>
                                    <td><?php echo $value['dtregister'] ?></td>
                                    <td>
                                        <div class="ico">
                                            <a href="/admin/categoria/edit?id=<?php echo $value['idcategory']?>">
                                                <i class="fa-solid fa-user-pen" ></i> Editar 
                                            </a>
                                            <a href="#" onclick="deletarItem('categoria',
                                            <?php echo $value['idcategory']?>)" id="delete">
                                                <i class="fa-solid fa-user-xmark"></i> Deletar
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>


<script>
    $(function() {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true
        });
    });

</script>
</section>
<script>$('.treeview#categorie').addClass('active');</script>