<section class="content-header">
  <h1>
    Produtos da Categoria <?php echo $this->view->categoria['descategory'] ?>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/admin/categorias">Categorias</a></li>
    <li><a href="/admin/categorias"><?php echo $this->view->categoria['descategory'] ?></a></li>
    <li class="active"><a href="/admin/categoria/produtos?id=<?php echo $this->view->categoria['idcategory'] ?>">Produtos</a></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                <h3 class="box-title">Todos os Produtos</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <div class="box-body">
                    <table class="table table-striped" id="example1">
                        <thead>
                            <tr>
                                <th style="width: 15px">#</th>
                                <th>Nome do Produto</th>
                                <th style="width: 60px"></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->view->produtosDontCategoria as $key => $produto) {?>
                            <tr>
                                <td><?php echo $key+1 ?></td>
                                <td><?php echo $produto['desproduct'] ?></td>
                                <td>
                                    <a href="/admin/categories/add?idCate=<?php echo $this->view->categoria['idcategory'] ?>&idProd=<?php echo $produto['idproduct'] ?>" class="btn btn-primary btn-xs pull-right"><i class="fa fa-arrow-right"></i> Adicionar</a>
                                </td>
                            </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-header with-border">
                <h3 class="box-title">Produtos na Categoria <?php echo $this->view->categoria['descategory'] ?></h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <div class="box-body">
                    <table class="table table-striped" id="example2">
                        <thead>
                            <tr>
                                <th style="width: 15px">#</th>
                                <th>Nome do Produto</th>
                                <th style="width: 60px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->produtosCategoria as $key => $produto) {?>
                                <tr>
                                    <td><?php echo $key+1 ?></td>
                                    <td><?php echo $produto['desproduct'] ?></td>
                                    <td>
                                        <a href="/admin/categories/remove?idCate=<?php echo $this->view->categoria['idcategory'] ?>&idProd=<?php echo $produto['idproduct'] ?>" class="btn btn-primary btn-xs pull-right"><i class="fa fa-arrow-left"></i> Remover</a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>        
    </div>

</section>


<script>
    $(function() {
        $('#example1').DataTable({
            "paging": false,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": false,
            "autoWidth": true
        });
        $('#example2').DataTable({
            "paging": false,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": false,
            "autoWidth": true
        });
        
    });



</script>
</section>
<script>$('.treeview#categorie').addClass('active');</script>
<script>$('.treeview#categorie li.1').addClass('active');</script>