<section class="content-header">
    <h1>Editar Categoria</h1>
    <ol class="breadcrumb">
        <li class="active"><a href="/admin"><i class="fa fa-dashboard"></i> Categorias</a></li>
        <li><a href="/admin/categorias">Categorias</a></li>
        <li><a href="#">Edit</a></li>
    </ol>
</section>
<section class="content">

    <div class="row">
        <div class="col-md-12">
            <div class="box box-body">
                <form role="form" action="/admin/categoria/editar" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="descategory">Nome da categoria</label>
                            <input type="hidden" name="id" value="<?php echo $this->view->categoria['idcategory'] ?>">
                            <input type="text" class="form-control" id="descategory" name="nome" placeholder="Digite o nome da categoria" value="<?php echo $this->view->categoria['descategory'] ?>">
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>

<script>$('.treeview#categorie').addClass('active');</script>
<script>$('#nome').focus()</script>