<?php $this->loadComponent('title') ?>
<?php $frete = $this->view->cart->freight?>
<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container-cart">
        <div class="row">

            <div class="col-md-12">
                <div class="product-content-right">
                    <div class="woocommerce">
                        <?php $this->loadComponent('products') ?>

                        <div class="cart-collaterals">

                            <div class="cross-sells">

                                <h2>Cálculo de Frete</h2>
                                <form action="/cart/freight">
                                    <div class="coupon">
                                        <label for="cep">CEP:</label>
                                        <input type="text" placeholder="00000-000" id="cep" value="<?php echo $this->view->cep ?>" class="input-text" name="cep">
                                        <input type="submit" value="CALCULAR" class="button">
                                    </div>
                                </form>

                            </div>


                            <div class="cart_totals ">
                                <h2>Resumo da Compra</h2>
                                
                                <table cellspacing="0">
                                    <tbody>
                                        <tr class="cart-subtotal">
                                            <th>Subtotal</th>
                                            <td><span class="amount">R$<?php echo isset($this->view->subtotal[count($this->view->subtotal)-1]) ? number_format($this->view->subtotal[count($this->view->subtotal)-1],2,',','.') : "0,00"?></span></td>
                                        </tr>

                                        <tr class="shipping">
                                            <th>Frete</th>
                                            <td>R$<?php echo ($frete!=0) ? number_format($frete, 2,',','.') : "0,00"?></td>
                                        </tr>
                                        <tr>
                                            <th>Prazo</th>
                                            <td><?php echo $this->view->cart->nrdays ?> Dias Úteis</td>
                                        </tr>

                                        <tr class="order-total">
                                            <th>Total</th>
                                            <td><strong><span class="amount">R$<?php echo isset($this->view->subtotal[count($this->view->subtotal)-1]) ? number_format($this->view->subtotal[count($this->view->subtotal)-1] + $frete,2,',','.') : "0,00"?></span></strong> </td>
                                        </tr>
                                    </tbody>
                                </table>
                            
                            </div>

                        </div>

                        <form class="pull-right" action="/checkout" method="POST">
                            <input type="submit" value="Finalizar Compra" class="checkout-button button alt wc-forward">
                        </form>

                    </div>
                </div>
            </div>
        </div>
</div>

<script>activeItem('cart')</script>