<section class="content-header">
    <h1> Todos os Produtos</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/admin/produtos">Produtos</a></li>
        <li class="active"><a href="/admin/produtos">Todos</a></li>
    </ol>
</section>
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-dark table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>photo</th>
                                <th>Nome</th>
                                <th>Preço</th>
                                <th>Dimensões</th>
                                <th>Peso</th>
                                <th>Registro</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->produtos as $key => $value) { ?>
                                <?php
                                    $prodName = (strlen($value['desproduct']) > 60) ? substr($value['desproduct'], 0, 60) . "..." : $value['desproduct']; 
                                    $data = new DateTime($value['dtregister']);
                                    $data = str_replace('-','/',$data->format('d-m-Y'));
                                ?>
                                <tr>
                                    <td><?php echo $key + 1 ?></td>
                                    <td>
                                        <img src="<?php echo $value['photo']; ?>" style="width: 100px; height: 100px; object-fit: contain;">
                                    </td>
                                    <td><abbr title="<?php echo $value['desproduct'] ?>"><?php echo $prodName ?></abbr></td>
                                    <td>R$ <?php echo number_format($value['vlprice'], 2, ',', '.') ?></td>
                                    <td><?php echo $value['vlheight'] . " X " . $value['vlwidth'] . " X " . $value['vllength'] ?> cm</td>
                                    <td><?php echo $this->transformWeightNumber($value['vlweight']) ?></td>
                                    <td><?php echo $data ?></td>
                                    <td>
                                        <div class="ico" style="display: flex; flex-direction: column;">
                                            <a href="/admin/produto/edit?id=<?php echo $value['idproduct'] ?>" style="margin: 1rem 0;">
                                                <i class="fa-solid fa-user-pen"></i> Editar
                                            </a>
                                            <a href="/admin/produto/categorias?id=<?php echo $value['idproduct']?>">
                                                <i class="fa-solid fa-user-check" ></i> Categorias 
                                            </a>
                                            <a href="#" onclick="deletarItem('produto',<?php echo $value['idproduct'] ?>)" id="delete" style="margin: 1rem 0;">
                                                <i class="fa-solid fa-user-xmark"></i> Deletar
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<?php




?>


<script>
    $(function() {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true
        });
    });
</script>
</section>
<script>$('.treeview#prod').addClass('active');</script>
<script>$('.treeview#prod li.1').addClass('active');</script>