<?php $this->loadComponent('title') ?>

<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <?php foreach ($this->view->produtos as $key => $produto) {?>
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <a href="/productsDetails?url=<?php echo $produto['desurl'] ?>">
                            <div class="product-upper">
                                <img src="<?php echo $produto['photo'] ?>" style="object-fit: contain; width: 300px; height: 300px;">
                            </div>
                        </a>
                        <h2><a href="/productsDetails?url=<?php echo $produto['desurl'] ?>"><?php echo $produto['desproduct'] ?></a></h2>
                        <div class="product-carousel-price">
                            <!-- <ins>$899.00</ins> <del>$999.00</del> -->
                            <ins>R$<?php echo number_format($produto['vlprice'],2,",",".") ?></ins>
                        </div>  
                        
                        <div class="product-option-shop">
                            <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="<?php echo $produto['idproduct'] ?>" rel="nofollow" href="#">Add to cart</a>
                            <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="<?php echo $produto['idproduct'] ?>" rel="nofollow" href="#">Comprar</a>
                            
                        </div>                       
                    </div>
                </div>
             <?php } ?>
            
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="product-pagination text-center">
                    <nav>
                        <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        </ul>
                    </nav>                        
                </div>
            </div>
        </div>
    </div>
</div>

<script>activeItem('prod')</script>