<?php $this->loadComponent('title') ?>   
<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="single-sidebar">
                    <h2 class="sidebar-title">Buscar Produtos</h2>
                    <form action="">
                        <input type="text" placeholder="Buscar produtos...">
                        <input type="submit" value="Buscar">
                    </form>
                </div>
                
                <div class="single-sidebar">
                    <h2 class="sidebar-title">Produtos</h2>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>                             
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>                             
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>                             
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>                             
                    </div>
                </div>

            </div>
            
            <div class="col-md-8">
                <div class="product-content-right">
                    <div class="product-breadcroumb">
                        <a href="">Home</a>
                        <a href="/produtos">Produtos</a>
                        <a href="">Category Name</a>
                        <a href=""><?php echo $this->view->produto['desproduct'] ?></a>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product-images">
                                <div class="product-main-img">
                                    <img src="<?php echo $this->view->produto['photo'] ?>" alt="">
                                </div>
                                
                                <!-- <div class="product-gallery">
                                    <img src="img/product-thumb-1.jpg" alt="">
                                    <img src="img/product-thumb-2.jpg" alt="">
                                    <img src="img/product-thumb-3.jpg" alt="">
                                </div> -->
                            </div>
                        </div>
                        
                        <div class="col-sm-6">
                            <div class="product-inner">
                                <h2 class="product-name"><?php echo $this->view->produto['desproduct'] ?></h2>
                                <div class="product-inner-price">
                                    <ins>R$ <?php echo number_format($this->view->produto['vlprice'],2,',','.') ?></ins>
                                </div>    
                                
                                <form action="#" class="cart">
                                    <div class="quantity">
                                        <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
                                    </div>
                                    <button class="add_to_cart_button" type="submit">Add to cart</button>
                                </form>   
                                
                                <div class="product-inner-category">
                                    <p>Category: <a href="">#</a>.
                                </div> 
                                
                                <div role="tabpanel">
                                    <ul class="product-tab" role="tablist">
                                        <li role="presentation" class="homeItem active" onclick="ativarItem('homeItem')"> 
                                            <a href="#home" aria-controls="home" role="tab" data-toggle="tab">
                                                Descrição
                                            </a>
                                        </li>
                                        <li role="presentation" class="profile" onclick="ativarItem('profile')">
                                            <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">
                                                Comentarios
                                            </a>
                                        </li>
                                    </ul>
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="homeItem">
                                            <h2>Descrição do Produto</h2>  
                                            <p><?php echo $this->view->produto['descricao'] ?></p>
                                        </div>
                                        <div role="tabpane2" class="tab-pane fade" id="profile">
                                            <h2>Comentarios</h2>
                                            <div class="submit-review">
                                                <p><label for="name">Name</label> <input name="name" type="text"></p>
                                                <p><label for="email">Email</label> <input name="email" type="email"></p>
                                                <div class="rating-chooser">
                                                    <p>Your rating</p>

                                                    <div class="rating-wrap-post">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <p><label for="review">Your review</label> <textarea name="review" id="" cols="30" rows="10"></textarea></p>
                                                <p><input type="submit" value="Submit"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    
                </div>                    
            </div>
        </div>
    </div>
</div>
<script>
    const ativarItem = id => {
        document.querySelectorAll('ul.product-tab li').forEach(li => {
            li.classList.remove('active')
        })
        document.querySelectorAll('div.tab-content div.fade').forEach(li => {
            li.classList.remove('active')
        })
        
        // console.log(document.querySelector(`#${id}`))
        // console.log(document.querySelector(`.${id}`))
        document.querySelector(`#${id}`).classList.add('in')
        document.querySelector(`#${id}`).classList.add('active')
        document.querySelector(`.${id}`).classList.add('active')
    }
</script>
<script>activeItem('prod')</script>