<?php $this->loadComponent('title') ?>

<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    
    <div class="container">
        <div class="row">

            <div class="col-md-4">
                 <?php $this->loadComponent('othersProducts') ?>
            </div>

            <div class="col-md-8">
                <div class="product-content-right">
                    <?php $this->loadComponent('broadMenu') ?>

                    <div class="row">
                        <div class="col-sm-6"> <?php $this->loadComponent('mainProduct')?></div>
                        <div class="col-sm-6"> <?php $this->loadComponent('productDetails') ?></div>
                    </div>
                </div>
            </div>
        </div>
        <?php $this->loadComponent('coments') ?>
    </div>
</div>

<script>activeItem('cart')</script>