<?php

use App\Models\Message;

if (isset($_SESSION['msg']) && !empty($_SESSION['msg'])) {

    $message = Message::getMessage();

    $this->view->type = $message['type'];
    $this->view->message = $message['msg'];
    $this->view->time = $message['time'];


    Message::cleanMessage();

    unset($message);
    unset($msg);
    
    ?>

    <script>
        function delToast() {
            setTimeout(() => {
                apagarToast()
            }, 3500);
        }

        function apagarToast() {
            $('#toast').remove()
        }
    </script>

    <div class="toast border-<?php echo $this->view->type ?>" role="alert" id="toast" aria-live="assertive" aria-atomic="true" style=" position: fixed; top: 5rem; right: 8rem; opacity: 1;width: 33rem;">
        <div class="toast-header" style="margin-bottom: 1rem;">
            <strong class="me-auto text-<?php echo $this->view->type ?>"><?php echo $this->view->type ?></strong>
            <small class="text-muted"><?php echo $this->view->time ?> seconds ago</small>
            <button type="button" class="btn-close close" data-bs-dismiss="toast" aria-label="Close" onclick="$('#toast').remove()"> <i class="fa fa-times" aria-hidden="true"></i> </button>
        </div>
        <div class="toast-body">
            <?php echo $this->view->message ?>
        </div>
    </div>

    <script>
        delToast()
    </script>
<?php } ?>
