<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?php echo $this->view->title ?> | ECommerce | </title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="/css/admin/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="/css/admin/AdminLTE.min.css">
  <link rel="stylesheet" href="/css/toast.css">

</head>

<body class="hold-transition lockscreen">
  <div class="lockscreen-wrapper">

    <div class="help-block text-center">
      Olá <?php echo $this->view->nome ?>, digite uma nova senha:
    </div>
    <div class="lockscreen-item">
      <form action="/login/forgotPassword/resetPassword" method="post">
        <input type="hidden" name="code" value="<?php echo $this->view->code ?>">
        <input type="hidden" name="idRecovery" value="<?php echo $this->view->id ?>">
        <div class="input-group">
          <input type="password" class="form-control" placeholder="Digite a nova senha" name="password">
          <div class="input-group-btn">
            <button type="submit" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
          </div>
        </div>
      </form>
    </div>

    <div class="lockscreen-footer text-center">
      Copyright &copy; 2023 <b><a href="#" class="text-black">Ecommerce Store</a></b><br>
      All rights reserved
    </div>
  </div>
  <script src="/js/admin/jquery-2.2.3.min.js"></script>
  <script src="/js/admin/bootstrap.min.js"></script>
</body>

</html>