<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- METATAGS -->
    <?php $this->loadComponent('default') ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/css/admin/bootstrap.min.css">
    <link rel="stylesheet" href="/css/admin/AdminLTE.min.css">
    <link rel="stylesheet" href="/css/admin/skin-blue.min.css">
    <link rel="stylesheet" href="/css/toast.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="js/admin/jquery-2.2.3.min.js" defer></script>
    <script src="js/admin/bootstrap.min.js" defer></script>
    <script src="js/admin/app.min.js" defer></script>

    <title><?php echo $this->view->title ?> | ECommerce | </title>
</head>

<body class="hold-transition skin-blue sidebar-mini sidebar-collapse">
    <div class="wrapper">
        <?php $this->loadComponent('toast') ?>
        <?php $this->loadComponent('admin/header') ?>
        <?php $this->loadComponent('admin/sidebar') ?>
        <div class="content-wrapper">
            <?php $this->content() ?>
            
        </div>
        <?php $this->loadComponent('admin/controlBar') ?>


    </div>
</body>


</html>