<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- METATAGS -->
    <?php $this->loadComponent('default') ?>
    <?php $this->loadComponent('fontAwesome') ?>
    <link rel="stylesheet" href="/css/admin/bootstrap.min.css">
    <link rel="stylesheet" href="/css/admin/AdminLTE.min.css">
    <link rel="stylesheet" href="/css/admin/_all-skins.min.css">
    <link rel="stylesheet" href="/css/admin/style.css">
    <link rel="stylesheet" href="/css/toast.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" ></script>
    <script src="/js/admin/jquery-2.2.3.min.js" ></script>
    <script src="/js/admin/bootstrap.min.js" ></script>
    <script src="/js/admin/app.min.js" defer></script>
    <script src="/js/admin/demo.js" defer></script>

    <title><?php echo $this->view->title ?> | ECommerce | </title>
</head>

<body class="hold-transition skin-blue sidebar-mini sidebar-collapse">

    
    <div class="wrapper">
        <?php $this->loadComponent('toast') ?>

        <?php $this->loadComponent('admin/header') ?>
        <?php $this->loadComponent('admin/sidebar') ?>

        <div class="content-wrapper">
            <?php $this->content() ?>
            
        </div>
        <?php $this->loadComponent('admin/controlBar') ?>

        <div class="control-sidebar-bg"></div>
    </div>
</body>


</html>