<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!-- METATAGS -->
	<?php $this->loadComponent('default') ?>


	<?php $this->loadComponent('bootstrap') ?>
	<?php $this->loadComponent('fontAwesome') ?>
	<?php $this->loadComponent('jquery') ?>
	
	<link rel="stylesheet" type="text/css" href="/css/style.css">

	<title></title>
</head>
<body>
	<?php $this->loadComponent('toast')?>
	<?php $this->content() ?>
</body>
</html>