<?php

$routesRoutes['boleto'] = array(
    'route' => '/boleto',
    'controller' => 'BoletoController',
    'action' => 'boleto'
);  

$routesRoutes['adminBoleto'] = array(
    'route' => '/admin/boleto',
    'controller' => 'BoletoController',
    'action' => 'adminBoleto'
); 

$routesRoutes['boletoOnePage'] = array(
    'route' => '/pedido/boleto',
    'controller' => 'BoletoController',
    'action' => 'boletoOnePage'
); 


?>