<?php

$routesRoutes['setComent'] = array(
    'route' => '/setComents',
    'controller' => 'ComentController',
    'action' => 'setComent'
); 

$routesRoutes['like'] = array(
    'route' => '/like',
    'controller' => 'ComentController',
    'action' => 'like'
); 

$routesRoutes['unlike'] = array(
    'route' => '/unlike',
    'controller' => 'ComentController',
    'action' => 'unlike'
); 

$routesRoutes['desfazerLike'] = array(
    'route' => '/desfazerLike',
    'controller' => 'ComentController',
    'action' => 'desfazer'
); 
$routesRoutes['desfazerUnlike'] = array(
    'route' => '/desfazerUnlike',
    'controller' => 'ComentController',
    'action' => 'desfazer'
); 
?>