<?php

use MF\Model\Container; ?>
<div class="container-coments" id="coments">
    <h1>Comentarios</h1>

    <div class="row">
        <?php foreach ($this->view->coments as $key => $coment) { ?>
            <?php
            $subject = (strlen($coment['subject']) > 80) ? substr($coment['subject'], 0, 80) . "..." : $coment['subject'];
            $data = new DateTime($coment['dtregister']);
            $data = str_replace('-', '/', $data->format('d-m-Y H:i'));

            if (isset($_SESSION['iduser'])) {
                $comentModel = Container::getModel('coment');
                $comentModel->__set('id', $coment['idcoment']);
                $comentModel->__set('idUser', $_SESSION['iduser']);
                $ifLike = $comentModel->getIfComent();
                $coment['like'] = $comentModel->getLike();
                $coment['unlike'] = $comentModel->getUnlike();
            }
            ?>
            <div class="single-coment col-md-5 offset-col-md-1">
                <div class="coment-header-top">
                    <img src="/img/perfil/<?php echo $coment['perfil'] ?>">
                    <span><?php echo $coment['desperson'] ?></span>
                </div>
                <div class="coment-header-bottom">
                    <div class="rating">
                        <?php for ($i = 1; $i <= 5; $i++) { ?>
                            <?php if ($i <= $coment['rating']) { ?>
                                <i class="fa fa-star selected"></i>
                            <?php } else { ?>
                                <i class="fa fa-star"></i>
                            <?php } ?>
                        <?php } ?>
                        <span class="rating"><?php echo $coment['rating'] ?> de 5</span>
                    </div>
                    <div class="subject">
                        <abbr title="<?php echo $coment['subject'] ?>">
                            <?php echo $subject ?>
                        </abbr>
                    </div>
                </div>
                <div class="coment-body">
                    <p><?php echo $coment['coment'] ?></p>
                </div>
                <div class="coment-footer-top">
                    <?php if (isset($_SESSION['iduser'])) { ?>
                        <!-- SE TIVER LOGADO -->
                        <?php if ($ifLike[0] == true) { ?>
                            <!-- SE DEU VOTOU NESSE COMENT -->
                            <?php if ($ifLike[1] == 1) { ?>
                                <span class="ico">
                                    <a href="/desfazerLike?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-up" style="color: blue;"></i></a>
                                    <?php echo (empty($coment['like'])) ? 0 : $coment['like'] ?>
                                </span>
                                <span class="ico">
                                    <a href="/unlike?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-down" style="color: black;"></i></a>
                                    <?php echo (empty($coment['unlike'])) ? 0 : $coment['unlike'] ?>
                                </span>
                                <!-- LIKE -->
                            <?php } else { ?>
                                <!-- DESLIKE -->
                                <span class="ico">
                                    <a href="/like?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-up" style="color: black;"></i></a>
                                    <?php echo (empty($coment['like'])) ? 0 : $coment['like'] ?>
                                </span>
                                <span class="ico">
                                    <a href="/desfazerUnlike?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-down" style="color: red;"></i></a>
                                    <?php echo (empty($coment['unlike'])) ? 0 : $coment['unlike'] ?>
                                </span>

                            <?php } ?>

                        <?php } else { ?>
                            <span class="ico">
                                <a href="/like?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-up" style="color: black;"></i></a>
                                <?php echo (empty($coment['like'])) ? 0 : $coment['like'] ?>
                            </span>
                            <span class="ico">
                                <a href="/unlike?idComent=<?php echo $coment['idcoment'] ?>&iduser=<?php echo $_SESSION['iduser'] ?>"><i class="fa-solid fa-thumbs-down" style="color: black;"></i></a>
                                <?php echo (empty($coment['unlike'])) ? 0 : $coment['unlike'] ?>
                            </span>
                        <?php } ?>
                    <?php } else { ?>
                        <span class="ico">
                            <a href="#" onclick="alert('Para votar, faça login')">
                                <i class="fa-solid fa-thumbs-up" style="color: black;"></i>
                            </a>
                            <?php echo (empty($coment['like'])) ? 0 : $coment['like'] ?>
                        </span>
                        <span class="ico">
                            <a href="#" onclick="alert('Para votar, faça login')">
                                <i class="fa-solid fa-thumbs-down" style="color: black;"></i>
                            </a>
                            <?php echo (empty($coment['unlike'])) ? 0 : $coment['unlike'] ?>
                        </span>
                    <?php } ?>

                </div>
                <div class="coment-footer-bottom">
                    Comentario feito <?php echo $data ?>
                </div>

            </div>
        <?php } ?>

    </div>
</div>