<div class="product-images">
    <div class="product-main-img">
        <img src="<?php echo $this->view->produto['photo'] ?>" alt="">
    </div>
</div>
<div class="product-inner">
    <h2 class="product-name"><?php echo $this->view->produto['desproduct'] ?></h2>
    <div class="product-inner-price">
        <ins>R$ <?php echo number_format($this->view->produto['vlprice'], 2, ',', '.') ?></ins>
    </div>
    <?php if (isset($_SESSION['iduser'])) { ?>
        <form class="cart" method="POST">
            <div class="quantity">
                <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
            </div>
            <button class="add_to_cart_button">Add to cart</button>
        </form>
    <?php } else { ?>
        <h3 class="text-danger">Para comprar faça login</h3>
    <?php } ?>
    <div class="product-inner-category">
        <p>Categorias: </p>
        <ol type="I">
            <?php foreach ($this->view->categoria as $key => $categoria) { ?>
                <a href="/produtos?categoria=<?php echo $categoria['idcategory'] ?>" target="_blank">
                    <li><?php echo $categoria['descategory'] ?></li>
                </a>
            <?php } ?>
        </ol>
    </div>
</div>