<div class="product-images">
    <div class="product-main-img">
        <img src="<?php echo $this->view->produto['photo'] ?>" alt="">
    </div>
</div>
<div class="product-inner">
    <h2 class="product-name"><?php echo $this->view->produto['desproduct'] ?></h2>
    <div class="product-inner-price">
        <ins>R$ <?php echo number_format($this->view->produto['vlprice'], 2, ',', '.') ?></ins>
    </div>
    <form class="cart" method="GET" action="/cart/add">
        <div class="quantity">
            <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
            <input type="hidden" name="idProduct" value="<?php echo $this->view->produto['idproduct'] ?>">
        </div>
        <button type="submit" class="add_to_cart_button">Add to cart</button>
    </form>
    <div class="product-inner-category">
        <p>Categorias: </p>
        <ol type="I">
            <?php foreach ($this->view->categoria as $key => $categoria) { ?>
                <a href="/produtos?categoria=<?php echo $categoria['idcategory'] ?>" target="_blank">
                    <li><?php echo $categoria['descategory'] ?></li>
                </a>
            <?php } ?>
        </ol>
    </div>
</div>